#!/bin/sh
# entrypoint.sh — Runs once when the agent-aider container starts.
# Configures git identity and GitHub HTTPS credentials, then parks the
# container so n8n can `docker exec` into it on demand.
#
# Repos must be cloned manually into /workspace before the first agent run:
#   docker exec -it agent-aider sh -c "cd /workspace && git clone https://github.com/anthonycoffey/REPO.git"

set -e

# ── Git identity ──────────────────────────────────────────────────────────
git config --global user.name  "Bugsy"
git config --global user.email "bugsy@coffey.codes"

# ── GitHub HTTPS credential helper ───────────────────────────────────────
# GITHUB_TOKEN_AIDER must have: Contents (r/w), Pull requests (r/w),
# Issues (r/w) on the target repos. Set in .env as GITHUB_TOKEN_AIDER.
git config --global credential.helper store
printf "https://%s:x-oauth-basic@github.com\n" "${GITHUB_TOKEN_AIDER}" \
  > /root/.git-credentials
chmod 600 /root/.git-credentials

# ── Aider defaults (can be overridden per-invocation) ────────────────────
# Written to /root/.aider.conf.yml — aider reads this on every run.
cat > /root/.aider.conf.yml << EOF
# Auto-generated by entrypoint.sh — do not edit manually.
auto-commits: true
no-check-update: true
no-show-model-warnings: true
EOF

echo "[aider] Container ready. Workspace: /workspace"
echo "[aider] Repos present:"
ls /workspace 2>/dev/null || echo "  (none — clone repos before first run)"

# ── Park ─────────────────────────────────────────────────────────────────
exec tail -f /dev/null
